# Generated by Django 4.2.7 on 2025-11-16 19:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nombre_corto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre corto')),
                ('escudo', models.URLField(blank=True, null=True, verbose_name='URL del escudo')),
                ('id_api', models.IntegerField(unique=True, verbose_name='ID en API')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='URL del logo')),
                ('id_api', models.IntegerField(unique=True, verbose_name='ID en API')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'ordering': ['pais', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora')),
                ('goles_local', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Goles local')),
                ('goles_visitante', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Goles visitante')),
                ('estado', models.CharField(choices=[('NS', 'No iniciado'), ('LIVE', 'En vivo'), ('FT', 'Finalizado'), ('POST', 'Postpuesto'), ('CANC', 'Cancelado')], default='NS', max_length=10, verbose_name='Estado')),
                ('id_api', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID en API')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='partidos.equipo', verbose_name='Equipo local')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='partidos.equipo', verbose_name='Equipo visitante')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='partidos.liga', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha', 'estado'], name='partidos_pa_fecha_faee3b_idx'), models.Index(fields=['liga', '-fecha'], name='partidos_pa_liga_id_0b4fbc_idx')],
            },
        ),
    ]
