# Generated by Django 4.2.7 on 2025-11-16 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local_predicho', models.IntegerField(verbose_name='Goles local predicho')),
                ('goles_visitante_predicho', models.IntegerField(verbose_name='Goles visitante predicho')),
                ('prediccion_ia', models.TextField(blank=True, null=True, verbose_name='Análisis de IA')),
                ('confianza', models.FloatField(default=0.0, help_text='Nivel de confianza de la predicción (0-100)', verbose_name='Nivel de confianza')),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de predicción')),
                ('es_correcta', models.BooleanField(blank=True, null=True, verbose_name='¿Predicción correcta?')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='partidos.partido', verbose_name='Partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'ordering': ['-fecha_prediccion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_prediccion'], name='prediccione_usuario_25b9b1_idx'), models.Index(fields=['partido'], name='prediccione_partido_e4659b_idx')],
                'unique_together': {('usuario', 'partido')},
            },
        ),
    ]
